update citations for html
mesh-adaptation/movement pull request #132
Opened 2024-11-18 14:41 UTC by acse-ej321

Linked to https://github.com/mesh-adaptation/mesh-adaptation-docs/issues/50

should be evaluated in combination with:
https://github.com/mesh-adaptation/mesh-adaptation-docs/issues/50
https://github.com/mesh-adaptation/animate/pull/160
https://github.com/mesh-adaptation/goalie/pull/232

Locally the main warning remaining after all the PRs should be about 'duplicate_citations', though all citations should still render.

2024-11-18 17:55 UTC, jwallwork23 approved these changes

2024-11-18 18:03 UTC, jwallwork23 requested changes

2024-11-18 18:03 UTC, jwallwork23 commented on demos/demo_references.bib
Actually, don't we want to remove this bibtex file and just use the one in the docs repo?

2024-11-18 18:32 UTC, acse-ej321 commented on demos/demo_references.bib
I left the `demo_references.bib` file in each of the `./demos` folders and updated the `Makefile` to copy each into the one in the docs repo which is the collective reference.  The logic for including maintaining a `demo_references.bib` I think would be the convenience of adding any future demos and references to the same repository. 
@jwallwork23 - It would simplify the file structure even more to just add them to the one in docs repo. Should I do this?

2024-11-18 19:06 UTC, jwallwork23 commented on demos/demo_references.bib
Thanks, sorry that I didn't suggest this earlier!

2024-11-19 09:02 UTC, jwallwork23 approved these changes
Citations seem to work for Movement when I build locally, thanks.

2024-11-19 09:22 UTC, merged