Introduce optional dev dependencies
mesh-adaptation/movement pull request #143
Opened 2024-12-28 17:16 UTC by ddundo

See https://github.com/mesh-adaptation/animate/issues/167.

2024-12-29 10:49 UTC, jwallwork23 approved these changes

2024-12-29 11:42 UTC, jwallwork23 requested changes
I just realised we should have the CI trigger if `pyproject.toml` is changed, too, right? Similarly in the other PRs.

2024-12-29 12:49 UTC, ddundo commented
> I just realised we should have the CI trigger if `pyproject.toml` is changed, too, right? Similarly in the other PRs.

Yeah I thought the same after seeing how sloppy I was in this PR :) I opened https://github.com/mesh-adaptation/docs/pull/98 and tested it here now.

2024-12-29 12:49 UTC, ddundo commented on .github/workflows/test_suite.yml
> +    uses: mesh-adaptation/docs/.github/workflows/reusable_test_suite.yml@workflow_install_test
Change back to main branch after https://github.com/mesh-adaptation/docs/pull/98 merges

2024-12-31 13:01 UTC, jwallwork23 approved these changes
Thanks, looks good now.

2025-01-01 16:13 UTC, ddundo commented
> Thanks, looks good now.

I made the same change in other PRs which you already approved, so I will merge without requesting a review again :)

2025-01-01 16:13 UTC, merged