Doubly periodic MA demo
mesh-adaptation/movement pull request #144
Opened 2024-12-29 12:03 UTC by jwallwork23

Closes #25.

Introduces a new MA demo that checks things work as expected on a doubly periodic domain.

2025-01-07 13:16 UTC, ddundo requested changes
Nice demo! Just two minor comments.

Could you please also update the link to renamed monge_ampere_ring.py demo in the 3D demo? In line 35 https://github.com/mesh-adaptation/movement/blob/b090830180ed9ed39a84d4e0ead1e1bd197940f7/demos/monge_ampere_3d.py#L35

2025-01-07 13:16 UTC, ddundo commented on demos/monge_ampere_periodic.py
> +# Define the same monitor function and an instance of the :class:`~.MongeAmpereMover`
Link doesn't work, but it works if you write it in full `~movement.monge_ampere.MongeAmpereMover`

2025-01-07 13:16 UTC, ddundo commented on demos/monge_ampere_periodic.py
> +assert np.isclose(assemble(Constant(1.0, domain=mover.mesh) * dx), expected_area)
This raises a warning `/home/firedrake/firedrake/src/firedrake/firedrake/constant.py:73: FutureWarning: Giving Constants a domain is no longer supported. Instead please create a Function in the Real space.` I think this is equivalent to passing `domain` to the measure? This doesn't raise an error

```suggestion
assert np.isclose(assemble(Constant(1.0) * dx(domain=mover.mesh)), expected_area)
```

2025-01-07 13:16 UTC, ddundo commented on demos/monge_ampere_periodic.py
> +# Define the same monitor function and an instance of the :class:`~.MongeAmpereMover`
```suggestion
# Define the same monitor function and an instance of the
# :class:`~movement.monge_ampere.MongeAmpereMover` class. ::
```

2025-01-08 17:32 UTC, jwallwork23 commented on demos/monge_ampere_periodic.py
> +assert np.isclose(assemble(Constant(1.0, domain=mover.mesh) * dx), expected_area)
Ah okay, I'd missed that. I noticed there's also `domain_constant` now, too.

2025-01-08 18:58 UTC, ddundo approved these changes

2025-01-08 19:34 UTC, merged